### ISSUE TITLE
error with failed.tpl template

### ISSUE THREAD

**Issue by alfonsolr09** [rowanfuchs/PrestaShop-login-as-a-customer#6]
look that 
https://www.prestashop.com/forums/topic/444031-free-module-login-as-customer/?do=findComment&comment=3296734

**Comment by alfonsolr09** [comment]
hay una línea de código que debe modificarse en los archivos. loginascustomer / controller / front / login.php

ahora mismo existe este código, por lo que cuando el token es incorrecto o modificado nos muestra un error 500

$ this-> setTemplate ('fallado.tpl');
ahora se ve así

image.thumb.png.54a07b1ca664917408f1b2ff2b21cc0f.png

solución 1:

el módulo tiene una plantilla para mostrar cuando el token es incorrecto, pero no se estaba utilizando.

 

para usarlo debemos cambiar el código de arriba por este abajo

$ this-> setTemplate ('módulo: loginascustomer / views / templates / front / failed.tpl');
se verá así usando la plantilla

image.thumb.png.22552ba441352b397414e1feb2962573.png

extra: 

la plantilla es muy fea, pero te daré algunos consejos.
si desea que aparezca su encabezado web, puede hacer lo siguiente.


elimine todo el código de loginascustomer / views / templates / front / failed.tpl
y agregue este otro

{extiende archivo = 'página.tpl'}

{block name = "page_content"}
    <h2> {ls = 'No autorizado' mod = 'loginas'} </h2> <p class = "alerta alerta-peligro" >
     
        {ls = 'No está autorizado para usar esta función' mod = 'loginas'}
    </p> 
{/ block}
ahora se verá así

image.thumb.png.7c5a2287f75ad450f07c1535bd9193dd.png

**Comment by alfonsolr09** [comment]
I made two pull requests to fix the problems

**Comment by rowanfuchs** [comment]
thank you very much for this addition! I will add them to a new release.
